package gui;

import java.beans.PropertyVetoException;
import static listeners.FuncionesAuxiliares.mensajeBienvenida;
import static listeners.FuncionesAuxiliares.mensajeVentana;

/**
 *
 * @author Grupo 5
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    /**
     * Declaración de las vista Hospital 
     */
    public static VentanaHospital hospital = null;

    /**
     * Declaración de las vista Paciente 
     */
    public static VentanaPaciente paciente = null;

    /**
     * Declaración de las vista Medico 
     */
    public static VentanaMedico medico = null;

    /**
     * Declaración de las vista Consulta 
     */
    public static VentanaConsulta consulta = null;

    /**
     * Declaración de las vista ReportePaciente 
     */
    public static VentanaReportePaciente reportePaciente = null;

    /**
     * Declaración de las vista ReporteConsulta
     */
    public static VentanaReporteConsulta reporteConsulta = null;

    /**
     * Declaración de las vista  ReporteHospital
     */
        public static VentanaReporteHospital reporteHospital = null;

    /**
     * Declaración de las vista ReporteMedico
     */
    public static VentanaReporteMedico reporteMedico = null;

     /**
     * Crea una nueva forma de Consultas
     */
    public VentanaPrincipal() {
        initComponents();
        /**
         * Centra la ventana del jFrame
         */
        setLocationRelativeTo(null);
        mensajeBienvenida("Bienvenido","Sistema de gestión de consultas para Hospitales",this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskSistema = new javax.swing.JDesktopPane();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        mnuGestion = new javax.swing.JMenu();
        opcPacientes = new javax.swing.JMenuItem();
        opcMedicos = new javax.swing.JMenuItem();
        opcConsultasMedicas = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        opcDatosHospital = new javax.swing.JMenuItem();
        opcReportePacientes = new javax.swing.JMenuItem();
        opcReporteMedicos = new javax.swing.JMenuItem();
        opcReporteConsultas = new javax.swing.JMenuItem();
        opcHospital = new javax.swing.JMenuItem();
        opcSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gestión de consultas");
        setResizable(false);

        deskSistema.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout deskSistemaLayout = new javax.swing.GroupLayout(deskSistema);
        deskSistema.setLayout(deskSistemaLayout);
        deskSistemaLayout.setHorizontalGroup(
            deskSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        deskSistemaLayout.setVerticalGroup(
            deskSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        mnuSistema.setText("Archivo");
        mnuSistema.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        mnuGestion.setText("Gestionar");
        mnuGestion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        opcPacientes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        opcPacientes.setText("Pacientes");
        opcPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcPacientesActionPerformed(evt);
            }
        });
        mnuGestion.add(opcPacientes);

        opcMedicos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        opcMedicos.setText("Médicos");
        opcMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMedicosActionPerformed(evt);
            }
        });
        mnuGestion.add(opcMedicos);

        opcConsultasMedicas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        opcConsultasMedicas.setText("Consultas médicas");
        opcConsultasMedicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsultasMedicasActionPerformed(evt);
            }
        });
        mnuGestion.add(opcConsultasMedicas);

        mnuSistema.add(mnuGestion);

        mnuReportes.setText("Informes");
        mnuReportes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        opcDatosHospital.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        opcDatosHospital.setText("Hospital");
        opcDatosHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcDatosHospitalActionPerformed(evt);
            }
        });
        mnuReportes.add(opcDatosHospital);

        opcReportePacientes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        opcReportePacientes.setText("Pacientes");
        opcReportePacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReportePacientesActionPerformed(evt);
            }
        });
        mnuReportes.add(opcReportePacientes);

        opcReporteMedicos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        opcReporteMedicos.setText("Médicos");
        opcReporteMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReporteMedicosActionPerformed(evt);
            }
        });
        mnuReportes.add(opcReporteMedicos);

        opcReporteConsultas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        opcReporteConsultas.setText("Consultas médicas");
        opcReporteConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReporteConsultasActionPerformed(evt);
            }
        });
        mnuReportes.add(opcReporteConsultas);

        mnuSistema.add(mnuReportes);

        opcHospital.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        opcHospital.setText("Datos Hospital");
        opcHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcHospitalActionPerformed(evt);
            }
        });
        mnuSistema.add(opcHospital);

        opcSalir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        opcSalir.setText("Salir del sistema");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        mnuSistema.add(opcSalir);

        mnuPrincipal.add(mnuSistema);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deskSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskSistema)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcHospitalActionPerformed
        // TODO add your handling code here:
        /**
         * Verifica si la ventana ya se encuentra abierta
         */
        if (hospital==null)
        {
            // Crea la Forma
            hospital = new VentanaHospital(this);
            deskSistema.add(hospital);
            try 
            {
                // Maximiza
                hospital.setMaximum(true);
            } 
            catch (Exception error) {
                mensajeVentana("ERROR","No se logro abrir la ventana\n\nDescripción:"+error.getMessage(),this);
            }
            hospital.show();
        }
        else
        {       
            // Oculta y Mustra
            hospital.setVisible(false);
            hospital.setVisible(true);
        }
    }//GEN-LAST:event_opcHospitalActionPerformed

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        
        /**
        * Sale del sistema
        */
        System.exit(0);                    
    }//GEN-LAST:event_opcSalirActionPerformed

    private void opcMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMedicosActionPerformed
        /**
        * Verifica si la ventana ya se encuentra abierta
        */
        if (medico==null)
        {
            // Crea la Forma
            medico = new VentanaMedico(this);
            deskSistema.add(medico);
            try 
            {
                // Maximiza
                medico.setMaximum(true);
            } 
            catch (PropertyVetoException error) {
                mensajeVentana("ERROR","No se logro abrir la ventana\n\nDescripción:"+error.getMessage(),this);
            }
            medico.show();
        }
        else
        {            
            // Oculta y Mustra
            medico.setVisible(false);
            medico.setVisible(true);
        }

    }//GEN-LAST:event_opcMedicosActionPerformed

    private void opcPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcPacientesActionPerformed
        /**
        * Verifica si la ventana ya se encuentra abierta
        */
        if (paciente==null)
        {
            // Crea la Forma
            paciente = new VentanaPaciente(this);
            deskSistema.add(paciente);
            try 
            {
                // Maximiza
                paciente.setMaximum(true);
            } 
            catch (PropertyVetoException error) {
                mensajeVentana("ERROR","No se logro abrir la ventana\n\nDescripción:"+error.getMessage(),this);
            }
            paciente.show();
        }
        else
        {            
            // Oculta y Mustra
            paciente.setVisible(false);
            paciente.setVisible(true);
        }
    }//GEN-LAST:event_opcPacientesActionPerformed

    private void opcConsultasMedicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsultasMedicasActionPerformed
        /**
        * Verifica si la ventana ya se encuentra abierta
        */
        if (consulta==null)
        {
            // Crea la Forma
            consulta = new VentanaConsulta(this);
            deskSistema.add(consulta);
            try 
            {
                // Maximiza
                consulta.setMaximum(true);
            } 
            catch (PropertyVetoException error) {
                mensajeVentana("ERROR","No se logro abrir la ventana\n\nDescripción:"+error.getMessage(),this);
            }
            consulta.show();
        }
        else
        {            
            // Oculta y Mustra
            consulta.setVisible(false);
            consulta.setVisible(true);
        }
    }//GEN-LAST:event_opcConsultasMedicasActionPerformed

    private void opcReportePacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReportePacientesActionPerformed
        // TODO add your handling code here:
         if (reportePaciente==null)
        {
            // Crea la Forma
            reportePaciente = new VentanaReportePaciente(this);
            deskSistema.add(reportePaciente);
            try 
            {
                // Maximiza
                reportePaciente.setMaximum(true);
            } 
            catch (PropertyVetoException error) {
                mensajeVentana("ERROR","No se logro abrir la ventana\n\nDescripción:"+error.getMessage(),this);
            }
            reportePaciente.show();
        }
        else
        {            
            // Oculta y Mustra
            reportePaciente.setVisible(false);
            reportePaciente.setVisible(true);
        }
    }//GEN-LAST:event_opcReportePacientesActionPerformed

    private void opcReporteMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReporteMedicosActionPerformed
         // TODO add your handling code here:
         if (reporteMedico==null)
        {
            // Crea la Forma
            reporteMedico = new VentanaReporteMedico(this);
            deskSistema.add(reporteMedico);
            try 
            {
                // Maximiza
                reporteMedico.setMaximum(true);
            } 
            catch (PropertyVetoException error) {
                mensajeVentana("ERROR","No se logro abrir la ventana\n\nDescripción:"+error.getMessage(),this);
            }
            reporteMedico.show();
        }
        else
        {            
            // Oculta y Mustra
            reporteMedico.setVisible(false);
            reporteMedico.setVisible(true);
        }
    }//GEN-LAST:event_opcReporteMedicosActionPerformed

    private void opcReporteConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReporteConsultasActionPerformed
        // TODO add your handling code here:
         if (reporteConsulta==null)
        {
            // Crea la Forma
            reporteConsulta = new VentanaReporteConsulta(this);
            deskSistema.add(reporteConsulta);
            try 
            {
                // Maximiza
                reporteConsulta.setMaximum(true);
            } 
            catch (PropertyVetoException error) {
                mensajeVentana("ERROR","No se logro abrir la ventana\n\nDescripción:"+error.getMessage(),this);
            }
            reporteConsulta.show();
        }
        else
        {            
            // Oculta y Mustra
            reporteConsulta.setVisible(false);
            reporteConsulta.setVisible(true);
        }
    }//GEN-LAST:event_opcReporteConsultasActionPerformed

    private void opcDatosHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcDatosHospitalActionPerformed
        // TODO add your handling code here:
         if (reporteHospital==null)
        {
            // Crea la Forma
            reporteHospital = new VentanaReporteHospital(this);
            deskSistema.add(reporteHospital);
            try 
            {
                // Maximiza
                reporteHospital.setMaximum(true);
            } 
            catch (PropertyVetoException error) {
                mensajeVentana("ERROR","No se logro abrir la ventana\n\nDescripción:"+error.getMessage(),this);
            }
            reporteHospital.show();
        }
        else
        {            
            // Oculta y Mustra
            reporteHospital.setVisible(false);
            reporteHospital.setVisible(true);
        }
    }//GEN-LAST:event_opcDatosHospitalActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskSistema;
    private javax.swing.JMenu mnuGestion;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem opcConsultasMedicas;
    private javax.swing.JMenuItem opcDatosHospital;
    private javax.swing.JMenuItem opcHospital;
    private javax.swing.JMenuItem opcMedicos;
    private javax.swing.JMenuItem opcPacientes;
    private javax.swing.JMenuItem opcReporteConsultas;
    private javax.swing.JMenuItem opcReporteMedicos;
    private javax.swing.JMenuItem opcReportePacientes;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables
}
