package gui;

import clases.Hospital;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import listeners.LeerBinarios;

/**
 *
 * @author Grupo 5
 */
public class VentanaReporteHospital extends javax.swing.JInternalFrame {
   
    private Hospital datos= new Hospital();
    private java.awt.Frame ventana;
    private Integer numeroPaginas;
    private Integer paginaActual=1;
    /**
     * Crea una nueva forma de IFrameHospital
     * @param parent variable con la ventana padre
     */
    public VentanaReporteHospital(java.awt.Frame parent) {
        initComponents();
        ventana=parent;
        // Quita la Barra de título
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        cargarTodosDatos();
        this.setVisible(true);
    }
    
    /**
     * inicializa todos los métodos necesarios para cargar la información a la tabla
     */
    public void cargarTodosDatos(){
       
        leerDatos();
        darFormatoTabla();
        cargarDatos();
        Double cedula= Double.valueOf(1);
        numeroPaginas=(int)Math.ceil(cedula/10);
    }
    // Procedimiento para dar formato a la Tabla
    @SuppressWarnings("empty-statement")
    private void darFormatoTabla()
    {

        // Obtiene el Modelo de Datos
        DefaultTableModel modelo = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                    return false;
            }
        };

        
        // Añadimos columnas al modelo de datos
        modelo.addColumn("Nombre");
        modelo.addColumn("RUC");
        modelo.addColumn("Teléfono");

        // Coloca el Modelo en la Tabla
        tblDatos.setModel(modelo);
        
        // Color de los Encabezados
        tblDatos.getTableHeader().setBackground(Color.blue);
        tblDatos.getTableHeader().setForeground(Color.white);
        tblDatos.getTableHeader().setFont(new Font("Arial Black", Font.PLAIN, 15));
        tblDatos.setFont(new Font("Arial", Font.PLAIN, 15));
    }
    
    /**
     * carga los datos del hospital y los guarda en un arreglo
     */
    private void cargarDatos()
    {
        // Variable para el Query
        int iCuenta;
        int iMaxRows;

        // Variable para el modelo de la tabla
        DefaultTableModel tablaDatos = (DefaultTableModel) tblDatos.getModel();

        // Obtiene el Número de Datos
        iMaxRows = tablaDatos.getRowCount();

        // Ciclo para Borrar
        for (iCuenta=0; iCuenta<iMaxRows;iCuenta++)
             tablaDatos.removeRow(0);

        // Prepara los datos vacios iniciales
        Object [] fila = new Object[3];

        for(int i=paginaActual*15-15;i<paginaActual*15;i++){
            if(i<1){
                fila[0]=datos.getNombre();
                fila[1]=datos.getRuc();
                fila[2]=datos.getTelefono();

                // Agrega el Dato
                tablaDatos.addRow(fila);
            }
        }
        
        // Coloca el Modelo de Nueva Cuenta
        tblDatos.setModel(tablaDatos);

        // Ciclo para agrandar la altura de los Rows
        for (int iRow=0; iRow < tblDatos.getRowCount();iRow++)
        {
            // Coloca la Altura
            tblDatos.setRowHeight(iRow, 30);
        }
    }

    /**
     * obtiene los datos del archivo .dat
     */
    public void leerDatos(){
           //Verifica si existe el archivo para proceder a leerlo
        File archivo =new File("hospital.med");
        if(archivo.canRead()){
            //recupera los datos del archivo hospital y los guarda en la variable
            datos= LeerBinarios.obtenerHospital(ventana);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Datos Hospital");

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        btnSalir.setBackground(java.awt.Color.red);
        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(lblTitulo)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1000, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Sale de la Forma
        VentanaPrincipal.reporteConsulta=null;
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
